This notebook checks the data shuffeling.

In [45]:
import os 
import pytorch_lightning as pl
from pytorch_lightning.callbacks import EarlyStopping
from torchvision import datasets, transforms
import torch as th
from torch import nn, optim
import torch.nn.functional as F

class LitModel(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.l1 = nn.Linear(28 * 28, 10)

    def forward(self, x):
        return th.relu(self.l1(x))

    def training_step(self, batch, batch_idx):
        x, y = batch
        print(x[:,0])
        y_hat = self(x)
        loss = F.mse_loss(y_hat, y)
#         res = self._fake_metric()
#         res["loss"] = loss        
#         self.log_dict(res, prog_bar=False, logger=False)
#         print(early_stopping.wait_count)
        return loss

#     def _fake_metric(self):
#         return {'acc': self.data[self.current_epoch]}

    def configure_optimizers(self):
        return optim.Adam(self.parameters(), lr=0.02)

In [47]:
ds_size = 10
data = th.rand(ds_size, 28*28)
for i in range(ds_size):
    data[i, :] = i
train_ds = th.utils.data.TensorDataset(data, th.ones(ds_size, 10))
train_loader = th.utils.data.DataLoader(train_ds, batch_size=2, shuffle=True)
trainer = pl.Trainer(max_epochs=10,
                     limit_train_batches=1,
                     limit_val_batches=1,)
model = LitModel()
trainer.fit(model, train_loader)

GPU available: True, used: False
TPU available: None, using: 0 TPU cores

  | Name | Type   | Params
--------------------------------
0 | l1   | Linear | 7.9 K 
--------------------------------
7.9 K     Trainable params
0         Non-trainable params
7.9 K     Total params
0.031     Total estimated model params size (MB)


tensor([7., 1.])
tensor([1., 9.])
tensor([4., 2.])
tensor([3., 5.])
tensor([2., 4.])
tensor([8., 4.])
tensor([9., 2.])
tensor([6., 3.])
tensor([8., 1.])
tensor([5., 0.])



1

In [39]:
data.shape

torch.Size([10, 784])

In [41]:
data

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [2., 2., 2.,  ..., 2., 2., 2.],
        ...,
        [7., 7., 7.,  ..., 7., 7., 7.],
        [8., 8., 8.,  ..., 8., 8., 8.],
        [9., 9., 9.,  ..., 9., 9., 9.]])